Create UI favorite, Handle event, Fetch data
awesome-academy/Quick-Quotes pull request #11
Opened 2022-06-16 08:25 UTC by truongdc21

**Related Tickets**
- [#11Task 49755: Create UI Favorite Fragment  ](https://edu-redmine.sun-asterisk.vn/issues/49782)

**WHAT**
Task/49783
Task/49783

**Evidence (Screenshot or Video)**

**Review Checklist**

**Notes (Optional)**

2022-06-16 09:23 UTC, daolq-2712 reviewed
Pls check my comments!

2022-06-16 09:23 UTC, daolq-2712 commented on app/src/main/java/com/truongdc21/quickquotes/Presenter/FragmentFavorite/FavoriteFragmentPresenter.kt
> +    private val context: Context,
```suggestion
    private val mContext: Context,
```
thêm prefix``m`` luôn cho nó đồng bộ e!

2022-06-16 09:23 UTC, daolq-2712 commented on app/src/main/java/com/truongdc21/quickquotes/data/source/SearchDataSource.kt
>  }
tiện tay thêm 1 blank line ở cuối file luôn e!

2022-06-16 09:23 UTC, daolq-2712 commented on app/src/main/java/com/truongdc21/quickquotes/ui/fragment/FavoriteViewpagerFragment.kt
> +                        0 -> tab.text = context?.resources?.getString(R.string.quotes)
define thành ``Enum`` TAB_QUOTES (0), TAB_AUTHOR(1), TAB_TAG(2) cho nó clear đi e

2022-06-16 09:23 UTC, daolq-2712 commented on app/src/main/res/layout/fragment_favorite.xml
>      tools:context=".ui.fragment.FavoriteFragment">
```suggestion
    tools:context=".ui.fragment.FavoriteFragment"/>
```

2022-06-16 09:39 UTC, truongdc21 commented on app/src/main/java/com/truongdc21/quickquotes/ui/fragment/FavoriteViewpagerFragment.kt
> +                        0 -> tab.text = context?.resources?.getString(R.string.quotes)
@daolq-2712 sử dụng enum class hay sao anh?

2022-06-16 09:40 UTC, daolq-2712 commented on app/src/main/java/com/truongdc21/quickquotes/ui/fragment/FavoriteViewpagerFragment.kt
> +                        0 -> tab.text = context?.resources?.getString(R.string.quotes)
@truongdc21 
yep e

2022-06-16 09:46 UTC, truongdc21 commented on app/src/main/java/com/truongdc21/quickquotes/ui/fragment/FavoriteViewpagerFragment.kt
> +                        0 -> tab.text = context?.resources?.getString(R.string.quotes)
@daolq-2712 Hay là tạo biến hằng vậy a?

2022-06-17 01:05 UTC, daolq-2712 requested changes
Pls check my comments!

2022-06-17 01:05 UTC, daolq-2712 commented on app/src/main/java/com/truongdc21/quickquotes/utils/base/BaseActivity.kt
> +}
add 1 blank line!

2022-06-17 01:37 UTC, vietnh-1109 commented on app/src/main/java/com/truongdc21/quickquotes/Presenter/FragmentFavorite/FavoriteFragmentContact.kt
> +        fun setAdapterTag(mList : List<Tag>)
Sao view lại là "set" , đổi thành "show" nhé hoặc get success

2022-06-17 01:40 UTC, vietnh-1109 commented on app/src/main/java/com/truongdc21/quickquotes/ui/fragment/FavoriteFragment.kt
> +        mPresenter?.onStart()
tôi đang thấy ở onStart của các presenter ông ko khai triển gì bên trong , những method nào cần gọi ngay khi init presenter thì đưa hết vào đây nhé , đưngf gọi riêng

2022-06-17 02:17 UTC, vietnh-1109 commented on app/src/main/java/com/truongdc21/quickquotes/Presenter/FragmentSearch/SearchFragmentContact.kt
>          fun removeHistorySuccess()
tuong tu

2022-06-17 08:07 UTC, vietnh-1109 approved these changes

2022-06-17 08:07 UTC, merged